### ISSUE TITLE
 程序包me.wcy.music.api不存在

### ISSUE THREAD

**Issue by pony-yu** [ChanWong21/PonyMusic#1]
怎么程序包me.wcy.music.api不存在呢

**Comment by wangchenyan** [comment]
API里面应该只有一个fir的key，用于检查更新，由于涉及隐私，我没有提交，可以直接用一个空字符串代替。

**Comment by sosodespicable** [comment]
在哪写这个空字符串啊？

**Comment by wangchenyan** [comment]
现在不需要替换了，更新到最新代码即可。@sosodespicable
