### ISSUE TITLE
clone项目有错

### ISSUE THREAD

**Issue by RenHaiRenWjc** [ChanWong21/PonyMusic#11]
克隆项目到android studio现在有错，内容为：unsupported major.minor version 52.0 android studio，我查了stackoverflow，有的说是 compileSdkVersion 和buildToolsVersion版本不对，但是项目里都是23 ；还有的说是jdk需要1.8，所以想请问你的jdk是1.8吗？

**Comment by wangchenyan** [comment]
Compile Java Version 是 1.7
