### ISSUE TITLE
安装体验问题

### ISSUE THREAD

**Issue by wmdkanhai** [ChanWong21/PonyMusic#12]
1，显示不出我本地音乐列表，也就是首页中进去后没有显示本地音乐
2，播放在线音乐的时候，不能点击下一首，进行下一首的播放

**Comment by wangchenyan** [comment]
本地音乐是从系统媒体库扫描得到的，请检查下手机默认播放器是否能检测到你的音乐。
谢谢你的建议，我有空的话优化一下。

**Comment by wangchenyan** [comment]
@wmdkanhai 你好，已添加播放列表功能，将在线音乐加入播放列表即可顺序播放。
