### ISSUE TITLE
为什么加载不出来网络歌曲列表，也无法搜索了

### ISSUE THREAD

**Issue by ymb104** [ChanWong21/PonyMusic#14]

**Comment by wmdkanhai** [comment]
同问，我写了一个小demo，获取数据报403，应该是接口的问题吧

**Comment by wangchenyan** [comment]
@ymb104 @wmdkanhai 问题已解决，谢谢^_^

**Comment by wmdkanhai** [comment]
我的这边还是不行啊，在线获取音乐显示 加载中，
这个要怎么解决呢？

**Comment by wangchenyan** [comment]
@wmdkanhai 你好，麻烦pull下最新代码。

**Comment by wmdkanhai** [comment]
好的，能否加下qq，546048371，希望可以跟你学习

**Comment by wangchenyan** [comment]
@wmdkanhai 不好意思，QQ被公司的网络屏蔽了，有问题可以随时提issues或者微博私信哈

**Comment by wmdkanhai** [comment]
好的，
