### ISSUE TITLE
扫描音乐的方法容易导致AND异常

### ISSUE THREAD

**Issue by wudongjiang333** [ChanWong21/PonyMusic#17]
因为作者的扫描方法是直接在主线中运行的，如果我的SD卡中有1000首音乐，扫描时间过长，而且极易导致ANR异常（本人SD卡真的有1000首音乐），建议使用AsyncQueryHandler

**Comment by wangchenyan** [comment]
@wudongjiang333 感谢你的建议，我抽空优化一下。

**Comment by wudongjiang333** [comment]
已经解决了，可以关闭
