### ISSUE TITLE
关于缓存的问题

### ISSUE THREAD

**Issue by liqian685** [ChanWong21/PonyMusic#18]
这个项目可以把在线的音乐缓存到本地呢？如果可以的话机制是什么呢？

**Comment by wangchenyan** [comment]
@liqian685 你好，目前有音乐下载功能，使用http传输。

**Comment by liqian685** [comment]
@wangchenyan 我现在想做一个边听边缓存的功能，然后在离线的时候可以读取并播放缓存，不知道楼主有什么建议没有

**Comment by wangchenyan** [comment]
@liqian685 初步建议是听的时候如果是WiFi网络就顺便把MP3下载下来。

**Comment by liqian685** [comment]
@wangchenyan 现在倒是这么做的 但是看着 qq音乐 酷狗音乐 什么的，然后再看看自己做的这个 很不爽啊。mediaplayer 其实有缓存 不知道能不能把他的缓存弄出来 然后保存，或者把Mediaplayer改造一下不知道行不行得通

**Comment by wangchenyan** [comment]
@liqian685 最好是这样，你可以试一下~
