### ISSUE TITLE
兄弟 通知栏的点击事件哪里设置?

### ISSUE THREAD

**Issue by luziming** [ChanWong21/PonyMusic#19]
还有退出的时候,service还在唱,通知栏也没有退出

**Comment by wangchenyan** [comment]
@luziming 你好，要点击菜单“退出”才会停止播放。

**Comment by luziming** [comment]
那有没有什么方式可以让他在后台被销毁的同时也关闭服务呢  - -

**Comment by wangchenyan** [comment]
@luziming 在Activity关闭时关闭服务即可。
