### ISSUE TITLE
本地音乐不能检索

### ISSUE THREAD

**Issue by MuDeBin** [ChanWong21/PonyMusic#20]
请问你这个是扫描固定的音乐文件路径还是扫描存储盘所有目录，然后筛选出含有音乐的目录添加到本地目录作为播放目录，如果是后者，那这个就是有问题。

**Comment by wangchenyan** [comment]
@MuDeBin 你好，扫描音乐是扫描了系统的媒体库，如果检索不到，可以看一下系统自带播放器是否可以检索到。

**Comment by MuDeBin** [comment]
不能检索其他播放器，比如网易云下载的文件夹里的歌吗，我刚用不同手机试了下，自动检索只能检索到Music/DownLoad里的歌，其他路径的检索不到，还有对缺少词图的歌不能联网匹配。

**Comment by wangchenyan** [comment]
你好，我刚试了，云音乐下载的歌曲是可以检索到的，需要退出APP再重新启动。

**Comment by wangchenyan** [comment]
歌词会在线搜索的，但可能搜索不到，专辑封面不会。

**Comment by MuDeBin** [comment]
我的检索不到任何音乐，除了路径是Music/DownLoad里的歌。还有我的两个手机系统是flyme，都检索不到歌曲。

**Comment by wangyuan0217** [comment]
我的flyme 从来就没检索到过

**Comment by wangchenyan** [comment]
@wangyuan0217 没有测过魅族的机子，抽空找一台测试一下。

**Comment by MuDeBin** [comment]
我找别人的机子（360）测试过，可以扫描到。

**Comment by wangchenyan** [comment]
@MuDeBin 你好，已经解决了魅族手机扫描不到音乐的问题，如果你是魅族手机，请pull最新代码后尝试。

**Comment by MuDeBin** [comment]
非常感谢作者，已经可行。
