### ISSUE TITLE
请问一下弱网情况下解决ANR的方法是什么？ 我们项目中也遇到了这个问题

### ISSUE THREAD

**Issue by gejiashu** [ChanWong21/PonyMusic#22]

**Comment by wangchenyan** [comment]
MediaPlayer.prepareAsync()

**Comment by gejiashu** [comment]
看来我们遇到的不是一个问题，我们遇到的是播放网络歌曲的时候如果网络不好　歌曲正在缓冲　这个时候调用reset()这个方法　会造成app　ANR　这个我们了解到是一个系统bug，现在准备换用google 开源的ExoPlayer去解决这个问题了．

**Comment by wangchenyan** [comment]
ExoPlayer也是很不错的
