### ISSUE TITLE
希望做成一个p2p的开源音乐播放器

### ISSUE THREAD

**Issue by piiiiiiiiiiiiiii** [ChanWong21/PonyMusic#23]
在酷狗 云音乐及版本越来越收缩的情况下，国内可用的音乐资源越来越少。

提个建议，如果能做成基于p2p网络的播放器，类似qbittorrent这样的p2p客户端，同时集成音乐播放功能，可以有效避免国内这种越来越紧缩的状况。

.

**Comment by wangchenyan** [comment]
是个不错的主意~
