### ISSUE TITLE
播放过程断网

### ISSUE THREAD

**Issue by zhupengxiang** [ChanWong21/PonyMusic#25]
我想问下歌曲播放过程中，我断掉网络，怎么实现连上网络后继续播放呢

**Comment by wangchenyan** [comment]
监听下网络状况吧，如果连上了就重试。

**Comment by zhupengxiang** [comment]
我用demo 先播放歌曲， 然后马上断网 还能一直播放，直到歌曲播放完成。我很郁闷，我一点播放不可能整首歌曲都缓冲完成吧

**Comment by wangchenyan** [comment]
网速快的话会很快缓冲完的
