### ISSUE TITLE
7.0下不能下载,应该是权限问题

### ISSUE THREAD

**Issue by luziming** [ChanWong21/PonyMusic#26]

**Comment by wangchenyan** [comment]
授予读写存储权限了吗？

**Comment by luziming** [comment]
嗯  给了

**Comment by wangchenyan** [comment]
报的什么错？

**Comment by luziming** [comment]
不报错  就是点击了下载  弹吐司  正在下载 ....通知栏不会显示正在下载...也没有执行下载任务

**Comment by wangchenyan** [comment]
看样子应该是DownloadManager的问题了，麻烦提供下机型？

**Comment by PPLLock** [comment]
作者你好，我测试的机子是华为荣耀8青春版，Android 7.0系统，不能下载，点下载弹出提示正在下载，然后就么有反应了

**Comment by PPLLock** [comment]
现在好像能下载了，但我发现另外一个问题，下载后删除掉app再安装，下载的音乐不见了，是不是下载的音乐保存在app的安装目录？

**Comment by wangchenyan** [comment]
@MrVking 我测试了华为P9 EMUI 5.0 Android 7.0，下载是正常的，但是卸载应用后下载的歌曲确实被删了，猜测是系统把通过DownloadManager下载的文件在应用卸载时一并删除了。
