### ISSUE TITLE
无法显示天气

### ISSUE THREAD

**Issue by dxclass** [ChanWong21/PonyMusic#27]

**Comment by dxclass** [comment]
报的是无法获取城市信息

**Comment by wangchenyan** [comment]
@dxclass 定位失败吗？

**Comment by dxclass** [comment]
是啊  大牛

**Comment by wangchenyan** [comment]
@dxclass 你好，应该是没有高德定位apikey导致的，需要去高德定位网站申请apiley，然后在项目根目录下的**local.properties**文件中添加

>AMAP_KEY=xxxxxx

xxxxxx替换为高德定位的apikey

**Comment by fgmn** [comment]
你好，添加apikey之后还是不行，错误码是34，对应是定位失败无法获取城市信息，可能是什么原因呢？
