### ISSUE TITLE
在线音乐播放下一曲的问题

### ISSUE THREAD

**Issue by marren06** [ChanWong21/PonyMusic#28]
你好，学习了你的这个项目，写的非常好，想进一步学习并想把它自己的实际项目中去，但是我看在线音乐的播放只是单个播放  播放完毕就会自动播放本地音乐，怎么样才能实现在线音乐的顺序播放，现在音乐播放在线音乐主流都是自动播放下一首

**Comment by wangchenyan** [comment]
@xuekaiqi 你好，已添加播放列表功能，将在线音乐加入播放列表即可顺序播放。
