### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nbpzjy** [ChanWong21/PonyMusic#3]
Error:Could not find lrcview.jar (me.wcy.lrcview:lrcview:1.0.0).
Searched in the following locations:
    https://jcenter.bintray.com/me/wcy/lrcview/lrcview/1.0.0/lrcview-1.0.0.jar

**Comment by nbpzjy** [comment]
{
  "errors" : [ {
    "status" : 404,
    "message" : "Could not find resource"
  } ]
}

**Comment by wangchenyan** [comment]
抱歉，由于“lrcview”还在jcenter审核中，所以暂时无法使用，我已经去除了lrcview依赖，添加了源文件，你现在可以pull代码后使用。
