### ISSUE TITLE
getPlayService null?

### ISSUE THREAD

**Issue by wangyuan0217** [ChanWong21/PonyMusic#31]
在base页面 的getPlayService()方法，中 获取PlayService 为null的处理 为null的时候throw NullPointerException这样 获取getPlayService()的时候为null时不是还是会有问题

**Comment by wangchenyan** [comment]
@wangyuan0217 你好，正常情况下 BaseActivity.getPlayService() 是不会为 null 的，如果为 null 那么应用将无法正常运行，因此需要抛出异常。

**Comment by wangyuan0217** [comment]
可是这样app还是会闪退啊

**Comment by wangchenyan** [comment]
@wangyuan0217 麻烦贴下崩溃栈

**Comment by wangyuan0217** [comment]
![image](https://user-images.githubusercontent.com/12730214/31324110-ac95f262-ace1-11e7-9c8a-16a6d77d49b9.png)
![image](https://user-images.githubusercontent.com/12730214/31324116-b7e471f2-ace1-11e7-9bfe-71015f736f2c.png)

**Comment by wangchenyan** [comment]
@wangyuan0217 你是否在调用getPlayService()之前启动了PlayService并将对其的引用保存在AppCache中？

**Comment by wangyuan0217** [comment]
在Application启动的时候startService，并在SplashActivity进行bindService，onServiceConnected之后将PlayService实例保存到AppCache

**Comment by wangchenyan** [comment]
@wangyuan0217 我大概知道问题在哪里了，Application只有在进程被杀的时候才会重新启动，所以startService的时机不对，应该是在SplashActivity启动时去startService。

**Comment by wangyuan0217** [comment]
可是在SplashActivity开始的时候已经做了service为null然后bindService()操作了啊

**Comment by wangchenyan** [comment]
@wangyuan0217 方便给一份你的代码吗？我的邮箱是wangchenyan2015@qq.com

**Comment by wangyuan0217** [comment]
不好意思，项目是公司的项目，代码不方便的。不过还是谢谢你项目的帮助。
