### ISSUE TITLE
使用卡顿

### ISSUE THREAD

**Issue by chenyusheng** [ChanWong21/PonyMusic#32]
今天在掘金上看到了推荐，就顺手编译了一下

发现在魅族note3 上运行明显卡顿
是没有做好优化？

不过一个毕业作品做成这样已经很牛逼了，之前我自己的毕业设计也只是很普通的App，加油~

**Comment by wangchenyan** [comment]
@chenyusheng 你好，请问主要在哪些地方卡顿呢？我等下找个手机测试下。

**Comment by chenyusheng** [comment]
在首页的【我的音乐】中滑动列表卡顿
应该是adapter的getView（）中有耗性能操作

另外在切换夜间模式的时候也是明显的卡主了
这个建议把切换的逻辑放在侧滑栏收起之后执行

最后，真的没有找到你的天气预报在哪。。。

**Comment by Jdroida** [comment]
@chenyusheng 首页左划可以在侧边栏看到天气预报

**Comment by chenyusheng** [comment]
@Jdroida 估计在魅族上真的有问题

![image](https://user-images.githubusercontent.com/11496107/31710591-0a23e18a-b428-11e7-8d8e-bc4ef2ae4af3.png)

**Comment by wangchenyan** [comment]
@chenyusheng 请检查是否给予定位权限？

**Comment by wangchenyan** [comment]
@chenyusheng 如果还无法显示天气请参考https://github.com/wangchenyan/PonyMusic/issues/27
