### ISSUE TITLE
努比亚Z11启动闪退

### ISSUE THREAD

**Issue by jelly0925** [ChanWong21/PonyMusic#33]
辛苦了，目前使用的是努比亚Z11手机，系统是安卓6.0.1安装波尼1.2.3后启动闪退，希望修复一下，谢谢哦。

**Comment by wangchenyan** [comment]
@jelly0925 你好，我使用nubia Z11 miniS Android 6.0.1（没找到Z11）测试了一下，没有出现闪退的问题，麻烦您把/sdcard/PonyMusic/Log/文件夹下的日志文件贴出来，我看下是什么原因，谢谢！
