### ISSUE TITLE
关于音效调节失效问题

### ISSUE THREAD

**Issue by GramYang** [ChanWong21/PonyMusic#35]
你好，我是一个android初学者，最近学习了你的ponymusic，学到了很多东西，感谢你的无私分享。
测试ponymusic在使用音效调节功能时会出现失效的情况，我参考Timber这款软件上的设置试了一下，在我的三星S5上运行成功！！估计是requestCode的问题。
comment已提交，请参考

**Comment by wangchenyan** [comment]
@GramYang 感谢！
