### ISSUE TITLE
关于进度条拖动的问题！

### ISSUE THREAD

**Issue by DevXue** [ChanWong21/PonyMusic#37]
在播放音乐的情况下，  我快速的拖动进度条， 然而他还没有缓冲完毕(播放网络音频)， 这个时候进度条会快速的回到起点位置，  不知道啥情况，Pony是这样子的，  我现在就遇到这个问题，不知道博主有没有啥好的解决办法！

**Comment by DevXue** [comment]
博主， 上面我描述的可能不太清楚，   我发现的问题是：   如果打开某一首音乐的话，此时网络稍微差点，还没有缓冲完， 然而用户就拖动进度条了到了中间的位置，  那么此时  是不是应该在用户拖动的位置开始缓冲呢？  就是从中间开始缓冲  缓冲好之后从中间（拖动后的位置）开始播放，然后现在的问题是：即便是我拖动到了中间的位置，可是等他缓冲好  还是从头开始播放的···，  
你有啥好的办法么？  这个问题困然我好久了  得不到解决，希望提供个思路 谢谢！
我见网易云 QQ音乐播放器都实现了这个功能，  拖动到某一个位置  提示加载  加载好了就开始播放。

**Comment by wangchenyan** [comment]
@DevXue 你好，想要实现这种功能应该需要自己实现一个 MediaPlayer，原生 MediaPlayer 对于播放流媒体音频支持的不太好。

**Comment by DevXue** [comment]
@wangchenyan   我也听一个哥们建议我用别的播放器，   你觉得IjkPlayer怎么样？  我看到这个项目已经不维护了   不怎么敢用···，  还有个Google的ExoPlayer

**Comment by wangchenyan** [comment]
@DevXue 这两个都是比较优秀的开源播放器，建议你两个都尝试一下，然后你就知道到底该用哪个了。

**Comment by DevXue** [comment]
@wangchenyan 嗯嗯  多谢指点  ！我去看看
