### ISSUE TITLE
代码写法的疑问

### ISSUE THREAD

**Issue by JM0425** [ChanWong21/PonyMusic#39]
public static void init(Application application) {
        getInstance().onInit(application);
    }

    private void onInit(Application application) {
        mContext = application.getApplicationContext();
        ToastUtils.init(mContext);
        Preferences.init(mContext);
        ScreenUtils.init(mContext);
        CrashHandler.getInstance().init();
        CoverLoader.getInstance().init(mContext);
        application.registerActivityLifecycleCallbacks(new ActivityLifecycle());
    }
为什么不在init直接初始化，而又封装了一个onInit方法？

**Comment by wangchenyan** [comment]
@JM0425 我想了一下，也没想出来当时是怎么想的了，只记得当时挺纠结的，现在改成普通的单例了。
