### ISSUE TITLE
anr问题。

### ISSUE THREAD

**Issue by bxxasn** [ChanWong21/PonyMusic#44]
在PlayService中
01-23 10:26:57.986 13307 13335 W Binder : Caught a RuntimeException from the binder stub implementation.
--
201-23 10:26:57.986 13307 13335 W Binder : java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder com.mediatek.anrappmanager.IFrameworks.serviceManagerGetService(java.lang.String)' on a null object reference
301-23 10:26:57.986 13307 13335 W Binder : at com.mediatek.anrappmanager.ANRManagerNative$1.b(SourceFile:77)
401-23 10:26:57.986 13307 13335 W Binder : at com.mediatek.anrappmanager.ANRManagerNative$1.c(SourceFile:75)
501-23 10:26:57.986 13307 13335 W Binder : at com.mediatek.anrappmanager.ANRManagerNative$a.get(SourceFile:97)
601-23 10:26:57.986 13307 13335 W Binder : at com.mediatek.anrappmanager.ANRManagerNative.getDefault(SourceFile:35)
701-23 10:26:57.986 13307 13335 W Binder : at com.mediatek.anrappmanager.ANRAppManager.dumpMessageHistory(SourceFile:59)
801-23 10:26:57.986 13307 13335 W Binder : at android.app.ActivityThread$ApplicationThread.dumpMessageHistory(ActivityThread.java:1244)
901-23 10:26:57.986 13307 13335 W Binder : at android.app.ApplicationThreadNative.onTransact(ApplicationThreadNative.java:682)
1001-23 10:26:57.986 13307 13335 W Binder : at android.os.Binder.execTransact(Binder.java:451)
1101-23 10:26:57.996 13346 13371 W CrashReport: not anr file /data/anr/binderinfo
1201-23 10:26:58.003 13346 13371 W CrashReport: not anr file /data/anr/binderinfo
1301-23 10:26:58.004 13346 13371 W CrashReport: not anr file /data/anr/binderinfo
1401-23 10:26:58.010 13346 13371 W CrashReport: not anr file /data/anr/binderinfo
1501-23 10:26:58.011 13346 13371 W CrashReport: not anr file /data/anr/binderinfo
1601-23 10:26:58.023 13346 13371 W CrashReport: not anr file /data/anr/binderinfo
1701-23 10:26:58.024 13346 13371 W CrashReport: not anr file /data/anr/binderinfo
1801-23 10:26:58.030 13346 13371 W CrashReport: not anr file /data/anr/binderinfo
1901-23 10:26:58.297 13307 13332 W CrashReport: not anr file /data/anr/binderinfo
2001-23 10:26:58.299 13307 13332 W CrashReport: not anr file /data/anr/binderinfo
2101-23 10:26:58.299 13307 13335 W System.err: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder com.mediatek.anrappmanager.IFrameworks.serviceManagerGetService(java.lang.String)' on a null object reference
2201-23 10:26:58.301 13307 13335 W System.err: at com.mediatek.anrappmanager.ANRManagerNative$1.b(SourceFile:77)
2301-23 10:26:58.302 13307 13335 W System.err: at com.mediatek.anrappmanager.ANRManagerNative$1.c(SourceFile:75)
2401-23 10:26:58.304 13307 13335 W System.err: at com.mediatek.anrappmanager.ANRManagerNative$a.get(SourceFile:97)
2501-23 10:26:58.306 13307 13335 W System.err: at com.mediatek.anrappmanager.ANRManagerNative.getDefault(SourceFile:35)
2601-23 10:26:58.307 13307 13335 W System.err: at com.mediatek.anrappmanager.ANRAppManager.dumpMessageHistory(SourceFile:59)
2701-23 10:26:58.307 13307 13317 I art : Wrote stack traces to '/data/anr/traces.txt'
2801-23 10:26:58.308 13346 13371 D CrashReport: read trace first dump for create time!
2901-23 10:26:58.308 13307 13332 D CrashReport: read trace first dump for create time!
3001-23 10:26:58.309 13307 13335 W System.err: at android.app.ActivityThread$ApplicationThread.dumpMessageHistory(ActivityThread.java:1244)
3101-23 10:26:58.311 13307 13335 W System.err: at android.app.ApplicationThreadNative.onTransact(ApplicationThreadNative.java:682)
3201-23 10:26:58.313 13307 13335 W System.err: at android.os.Binder.execTransact(Binder.java:451)

**Comment by wangchenyan** [comment]
@bxxasn 这看起来不像是 PonyMusic 中的问题呢
