### ISSUE TITLE
程序进程关闭 音乐还会后台播发

### ISSUE THREAD

**Issue by liujiangshuai** [ChanWong21/PonyMusic#45]
你好！
        播放器设计的很棒，这里有个问题需要咨询一下，当我通过后台关闭应用时，音乐还会继续播放，通知栏的音乐任然存在，这块本身就是这样设计的吗？

**Comment by wangchenyan** [comment]
@liujiangshuai 你好，后台播放时，会开启一个前台服务，优先级比较高，不会被系统杀死，也是为了防止内存不足被系统杀死，所以用常规方式无法结束进程。使用播放器内的退出菜单即可停止播放。
