### ISSUE TITLE
播放错误！

### ISSUE THREAD

**Issue by Born-alone** [ChanWong21/PonyMusic#48]
你好 使用这个播放音频 播放错误 
http://120.132.18.193:8080/vod/2018/1/31/1517365405976596.aac 
播的是这个地址的音频

**Comment by Born-alone** [comment]
03-30 17:56:21.695 685-9540/? E/FFMPEGExtractor: FFMPEGExtractor Failed open file (err = -13): http://120.132.18.193:8080/vod/2018/1/31/1517365405976596.aac
03-30 17:56:21.696 687-14476/? E/GenericSource: initFromDataSource, cannot create extractor!
03-30 17:56:21.696 687-14476/? E/GenericSource: Failed to init from data source!
03-30 17:56:21.698 14374-14386/com.avcon.music E/MediaPlayerNative: error (1, -2147483648)
03-30 17:56:21.699 14374-14374/com.avcon.music E/MediaPlayer: Error (1,-2147483648)
03-30 17:56:21.699 14374-14374/com.avcon.music E/PlayService:  播放错误

**Comment by wangchenyan** [comment]
应该是非法播放地址吧
