### ISSUE TITLE
关于 AndroidStudio 版本和导入问题

### ISSUE THREAD

**Issue by ZhangLanqiu** [ChanWong21/PonyMusic#53]
首先感谢博主的项目，目前有几个问题想向博主咨询一下：
##### 1、AndroidStudio 版本问题
我目前的 OS 是 win7 , AndroidStudio版本是 2.2.2  ,在导入你的项目后基本是错误不断无法运行，所以请博主提供下你的运行环境和 AndroidStudio 版本.
##### 2、导入问题
目前 1.3.0 版本是否只能在您所在环境运行呢？ 希望博主有时间的时候能够回复一下，如果能说下解决思路就更好了，无论如何先谢谢博主了

**Comment by wangchenyan** [comment]
@ZhangLanqiu 请使用 AS 3.0 以上版本
