### ISSUE TITLE
arr 包下载不了

### ISSUE THREAD

**Issue by woyoudianhuai** [ChanWong21/PonyMusic#6]
compile 'im.fir:fir-sdk:latest.integration@aar'

**Comment by wangchenyan** [comment]
![a52d tmp](https://cloud.githubusercontent.com/assets/12638716/19956243/04a5cb22-a1c5-11e6-87bd-eebbbb3ec02f.jpg)
这两行代码有吗？
如果有还是sync失败的话可以直接把这个依赖删掉，只是自动更新用的。
