### ISSUE TITLE
关于部分手机出现状态栏无法控制。

### ISSUE THREAD

**Issue by EsZhangHome** [ChanWong21/PonyMusic#61]
无法控制的时候查看日志信息如下：
BroadcastQueue: Background execution not allowed: receiving Intent { act=me.wcy.music.S
经过查询发现是：target>=26时，APP发送的隐式广播连自己也收不到，0上限制。

1.只要intent的flag包含FLAG_RECEIVER_EXCLUDE_BACKGROUND则不允许该广播被接收。

2.对于隐式广播，如果没有包含FLAG_RECEIVER_INCLUDE_BACKGROUND也不允许被接收。

解决方法：
在 Notifier中 getRemoteViews方法中 按钮控制的时候分别加上：intent.setPackage("包名");，最后的代码如下：

 Intent playIntent = new Intent(StatusBarReceiver.ACTION_STATUS_BAR);
        playIntent.setPackage("me.wcy.music");
        playIntent.putExtra(StatusBarReceiver.EXTRA, StatusBarReceiver.EXTRA_PLAY_PAUSE);
        PendingIntent playPendingIntent = PendingIntent.getBroadcast(context, 0, playIntent, PendingIntent.FLAG_UPDATE_CURRENT);
        remoteViews.setImageViewResource(R.id.iv_play_pause, getPlayIconRes(isLightNotificationTheme, isPlaying));
        remoteViews.setOnClickPendingIntent(R.id.iv_play_pause, playPendingIntent);

        Intent nextIntent = new Intent(StatusBarReceiver.ACTION_STATUS_BAR);
        nextIntent.setPackage("me.wcy.music");
        nextIntent.putExtra(StatusBarReceiver.EXTRA, StatusBarReceiver.EXTRA_NEXT);
        PendingIntent nextPendingIntent = PendingIntent.getBroadcast(context, 1, nextIntent, PendingIntent.FLAG_UPDATE_CURRENT);
        remoteViews.setImageViewResource(R.id.iv_next, getNextIconRes(isLightNotificationTheme));
        remoteViews.setOnClickPendingIntent(R.id.iv_next, nextPendingIntent);

**Comment by wangchenyan** [comment]
感谢您的建议，该项目目前仅适配了 Android N，有时间会适配新版本。

**Comment by wangchenyan** [comment]
新版本已适配到 Android 14，欢迎体验
