### ISSUE TITLE
我下载的歌曲为什么不显示啊,而且这个播放音乐在模拟器一直断断续续,我在电脑是可以播放的,是不是三星的这个模拟器的问题

### ISSUE THREAD

**Issue by SwpuEsine** [ChanWong21/PonyMusic#65]
<img width="425" alt="截屏2023-01-05 上午7 00 16" src="https://user-images.githubusercontent.com/24284757/210665995-750a1db2-9c64-4189-87c1-5c9dcef607de.png">

**Comment by wangchenyan** [comment]
请检查下载的文件是否在媒体库可见
