### ISSUE TITLE
找不到依赖

### ISSUE THREAD

**Issue by JonYun** [ChanWong21/PonyMusic#66]
A problem occurred configuring root project 'ponymusic-master'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.github.wangchenyan:AutoRegister:1.4.3-beta02.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/github/wangchenyan/AutoRegister/1.4.3-beta02/AutoRegister-1.4.3-beta02.pom
       - https://dl.google.com/dl/android/maven2/com/github/wangchenyan/AutoRegister/1.4.3-beta02/AutoRegister-1.4.3-beta02.pom
       - https://repo.maven.apache.org/maven2/com/github/wangchenyan/AutoRegister/1.4.3-beta02/AutoRegister-1.4.3-beta02.pom
       - https://maven.aliyun.com/repository/public/com/github/wangchenyan/AutoRegister/1.4.3-beta02/AutoRegister-1.4.3-beta02.pom
       - https://jitpack.io/com/github/wangchenyan/AutoRegister/1.4.3-beta02/AutoRegister-1.4.3-beta02.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by JonYun** [comment]
更改为：com.github.wangchenyan:AutoRegister:1.4.3 就可以了

**Comment by wangchenyan** [comment]
已修正，感谢反馈！
