### ISSUE TITLE
404问题

### ISSUE THREAD

**Issue by huluohu** [ChanWong21/PonyMusic#68]
开发者你好，我在模拟器中打开，并且连上了自建的 api 服务，但是歌单广场和排行榜 点开详情页后都显示 404。
app如下图：
![image](https://github.com/wangchenyan/ponymusic/assets/7138642/5b78f560-e1b9-4b75-97b7-995a61cb83f7)

这是 api 的日志：
<img width="904" alt="image" src="https://github.com/wangchenyan/ponymusic/assets/7138642/24528d64-fa91-4b48-9ed0-be1147b486cc">

**Comment by wangchenyan** [comment]
我刚试了下是正常的，你可以用真机试试

**Comment by huluohu** [comment]
> 我刚试了下是正常的，你可以用真机试试

感谢回复，我再试试
