### ISSUE TITLE
BUG:歌单歌曲过多读取报错（1555首）

### ISSUE THREAD

**Issue by JackA1ltman** [ChanWong21/PonyMusic#69]
报错如下，点击歌单就会显示这个信息
![Screenshot_20231207-164505.jpg](https://github.com/wangchenyan/ponymusic/assets/82563979/03236215-b05e-4952-bec6-dc5418998cee)

**Comment by wangchenyan** [comment]
你好，这个是已知问题，并非APP的bug，而是歌单歌曲过多接口报错了
