### ISSUE TITLE
MediaPlayer的兼容性太差，Error(38,-1)错误

### ISSUE THREAD

**Issue by QQ690898091** [ChanWong21/PonyMusic#76]
一些MP3连接播放失败，浏览器正常播放，报错MediaPlayer的错误码38的常见错误，建议更换播放引擎。是有最新的media3或者ExoPlayer

**Comment by wangchenyan** [comment]
@QQ690898091 你好，最新版本播放内核已升级为 Media3 + ExoPlayer，欢迎尝试 https://github.com/wangchenyan/ponymusic/releases
