### ISSUE TITLE
com.android.tools.r8.kotlin.H的解决方案

### ISSUE THREAD

**Issue by QQ690898091** [ChanWong21/PonyMusic#78]
问题说明 ：
项目在直接运行到模拟器或者手机的时候是正常的，当进行打包成apk时，会报错：com.android.tools.r8.kotlin.H，原因应该是插件之间的兼容问题导致，项目中使用了好几个插件，特别是自动注册的路由插件存在的兼容问题。

具体修复方案：
buildscript {
    dependencies {
        classpath("com.github.wangchenyan:AutoRegister:1.4.3")
        classpath("com.android.tools:r8:8.2.42") //修复R8问题
    }
}

**Comment by wangchenyan** [comment]
感谢分享解决方案！

**Comment by xin0921** [comment]
天才！！！我哭了！！！牛逼！！！
