### ISSUE TITLE
大佬麻烦添加下收藏功能

### ISSUE THREAD

**Issue by zptqghsw** [ChanWong21/PonyMusic#79]
其他都很好用，能加收藏功能就完美了

**Comment by wangchenyan** [comment]
收藏歌曲还是歌单呢

**Comment by zptqghsw** [comment]
> 收藏歌曲还是歌单呢

歌曲，歌单已经有收藏功能了

**Comment by wangchenyan** [comment]
收到，这就安排

**Comment by wangchenyan** [comment]
@zptqghsw 兄弟，很遗憾的告诉你，当我把功能做完才发现，后端接口的作者没有提供收藏歌曲的接口😂，我只好先把 UI 实现了，再看看能不能找到接口

**Comment by zptqghsw** [comment]
/**
 * 喜欢音乐
 * 说明 : 调用此接口 , 传入音乐 id, 可喜欢该音乐
 * - id - 歌曲 id
 * - like - 默认为 true 即喜欢 , 若传 false, 则取消喜欢
 * @param {Object} params
 * @param {number} params.id
 * @param {boolean=} [params.like]
 */
export function likeATrack(params) {
  params.timestamp = new Date().getTime();
  return request({
    url: '/like',
    method: 'get',
    params,
  });
}
其他项目找的接口，你试试看

**Comment by zptqghsw** [comment]
https://github.com/qier222/YesPlayMusic
这里面接口很齐全

**Comment by zptqghsw** [comment]
/**
 * 对歌单添加或删除歌曲
 * 说明 : 调用此接口 , 可以添加歌曲到歌单或者从歌单删除某首歌曲 ( 需要登录 )
 * - op: 从歌单增加单曲为 add, 删除为 del
 * - pid: 歌单 id tracks: 歌曲 id,可多个,用逗号隔开
 * @param {Object} params
 * @param {string} params.op
 * @param {string} params.pid
 */
export function addOrRemoveTrackFromPlaylist(params) {
  params.timestamp = new Date().getTime();
  return request({
    url: '/playlist/tracks',
    method: 'post',
    params,
  });
}

**Comment by zptqghsw** [comment]
大佬，喜欢歌曲麻烦也加下哦，遇到喜欢的音乐可以加心

**Comment by zptqghsw** [comment]
https://musicapi.taptop.cn/
自建的api供大佬调试，这个可以解锁所有歌曲

**Comment by wangchenyan** [comment]
@zptqghsw 收藏歌曲到歌单加上了，可以用这个包试一下
[ponymusic-2.1.0-beta01.apk.zip](https://github.com/wangchenyan/ponymusic/files/14691629/ponymusic-2.1.0-beta01.apk.zip)

**Comment by zptqghsw** [comment]
可以使用，感谢大佬！
建议在播放页面加上喜欢的爱心按钮就更方便了

**Comment by wangchenyan** [comment]
@zptqghsw 喜欢也加上了
[ponymusic-2.1.0-beta01-20240322.apk.zip](https://github.com/wangchenyan/ponymusic/files/14720999/ponymusic-2.1.0-beta01-20240322.apk.zip)

**Comment by zptqghsw** [comment]
太赞了，好用！

**Comment by zptqghsw** [comment]
我看目前主流音乐软件把喜欢也会在通知栏控制页签上显示，大佬看有空的话可以加下
