### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by lishangwl** [ChanWong21/PonyMusic#83]
app/build.gradle

COMPILE_SDK_VERSION
BUILD_TOOLS_VERSION
MIN_SDK_VERSION
TARGET_SDK_VERSION
VERSION_CODE
VERSION_NAME
我知道可以写成固定的，好像源码里没有这些变量？

**Comment by wangchenyan** [comment]
这几个变量在 grade/libs.versions.toml 中

**Comment by lishangwl** [comment]
> 这几个变量在 grade/libs.versions.toml 中
build.gradle、build.gradle.kts，用的是kts？我看到gradle配置都是有一份kts的语法。

**Comment by lishangwl** [comment]
> > 这几个变量在 grade/libs.versions.toml 中
> > build.gradle、build.gradle.kts，用的是kts？我看到gradle配置都是有一份kts的语法。

难道你之前是用build.gradle。然后后面换了build.gradle.kts。但是github的没有删除build.gradle。所以存在2个？

**Comment by lishangwl** [comment]
> > > 这几个变量在 grade/libs.versions.toml 中
> > > build.gradle、build.gradle.kts，用的是kts？我看到gradle配置都是有一份kts的语法。
> 
> 难道你之前是用build.gradle。然后后面换了build.gradle.kts。但是github的没有删除build.gradle。所以存在2个？

果然是这样，旧的build.gradle文件还存在源码。手动删了，就好了

**Comment by lishangwl** [comment]
好吧 我好像知道问题，我之前就下载过这个源码。我好像覆盖的源码。所以导致这样的，关闭吧issues
