### ISSUE TITLE
可以实现边听边播吗？不是下载

### ISSUE THREAD

**Issue by aikorola** [ChanWong21/PonyMusic#84]
可以实现边听边播吗？不是下载，目前我看是全部加载完了才去播放，有时候服务器或者网络原因，就会特别慢

**Comment by wangchenyan** [comment]
@aikorola 你好，你指的是播放在线歌曲时，边缓冲边播吗？
目前 ExoPlayer 的实现应该就是拿到网络返回的 InputStream，边播边读取，不是一次性读取完

**Comment by aikorola** [comment]
@wangchenyan 对的，边缓冲边播，我拉下代码试试，我刚刚看的代码还是mediaplayer那个实现
