### ISSUE TITLE
求能正常运行该项目的gradle和gradle插件以及JDK的版本

### ISSUE THREAD

**Issue by YanZeno** [ChanWong21/PonyMusic#88]
求能正常运行该项目的gradle和gradle插件以及JDK的版本

**Comment by wangchenyan** [comment]
你好，master 分支最新的代码即可正常运行，如果不能运行，请尝试删除仓库，重新 clone。
如果还是有问题，可以把错误日志贴一下。

**Comment by YanZeno** [comment]
你好，很高兴收到你的回复，按照你说的我重新进行了clone，但是依旧与之前一样无法运行，
![J}4}0YI)MLN40F}I7F1PC$H](https://github.com/wangchenyan/ponymusic/assets/132640475/91da70cb-f2ad-4b4b-b8d7-d46b044c006e)
代码中的libs似乎有问题，
![K%(B@_(O}$_PL {BWHVO JT](https://github.com/wangchenyan/ponymusic/assets/132640475/c3bd1ca4-9f27-4e58-ba51-91a989e7f769)
我不知道该如何处理，AS提示我将gradle插件版本从7.4.2更新到8.3.2，
![image](https://github.com/wangchenyan/ponymusic/assets/132640475/9347b59d-554f-4422-9941-4c9da60e6679)
我之前尝试过，可以解决libs的爆红，但是这又会产生新的问题，由于版本更新后8.0以上的gradle插件会弃用auto-register的相关模块，这导致了项目无法运行成功，所以我不知道该如何在不更新gradle插件的前提下解决libs报错问题，另外不知道为什么这个jar包下会有这么多的报错
![S@LVJJSZIKAUKH09J0VG`P](https://github.com/wangchenyan/ponymusic/assets/132640475/4be7bee9-ad31-4c27-98d8-8f37127b7dfc)
![%H4YSD2888 EA$%PWBY7{7Y](https://github.com/wangchenyan/ponymusic/assets/132640475/7107fa26-501d-4fa2-a906-7c3878e5ab38)
sync过后AS给的警告也和版本有关
![image](https://github.com/wangchenyan/ponymusic/assets/132640475/fa32f3c5-dbe7-4358-b27b-b4b920e56678)
![image](https://github.com/wangchenyan/ponymusic/assets/132640475/31e20a96-5de2-417e-9632-1376f65f8dcc)
日志中的报红
![你好，很高兴收到你的回复，按照你说的我重新进行了clone，但是依旧与之前一样无法运行，
![J}4}0YI)MLN40F}I7F1PC$H](https://github.com/wangchenyan/ponymusic/assets/132640475/91da70cb-f2ad-4b4b-b8d7-d46b044c006e)
代码中的libs似乎有问题，
![K%(B@_(O}$_PL {BWHVO JT](https://github.com/wangchenyan/ponymusic/assets/132640475/c3bd1ca4-9f27-4e58-ba51-91a989e7f769)
我不知道该如何处理，AS提示我将gradle插件版本从7.4.2更新到8.3.2，
![image](https://github.com/wangchenyan/ponymusic/assets/132640475/9347b59d-554f-4422-9941-4c9da60e6679)
我之前尝试过，可以解决libs的爆红，但是这又会产生新的问题，由于版本更新后8.0以上的gradle插件会弃用auto-register的相关模块，这导致了项目无法运行成功，所以我不知道该如何在不更新gradle插件的前提下解决libs报错问题，另外不知道为什么这个jar包下会有这么多的报错
![S@LVJJSZIKAUKH09J0VG`P](https://github.com/wangchenyan/ponymusic/assets/132640475/4be7bee9-ad31-4c27-98d8-8f37127b7dfc)
![%H4YSD2888 EA$%PWBY7{7Y](https://github.com/wangchenyan/ponymusic/assets/132640475/7107fa26-501d-4fa2-a906-7c3878e5ab38)
sync过后AS给的警告也和版本有关
![image](https://github.com/wangchenyan/ponymusic/assets/132640475/fa32f3c5-dbe7-4358-b27b-b4b920e56678)
![image](https://github.com/wangchenyan/ponymusic/assets/132640475/31e20a96-5de2-417e-9632-1376f65f8dcc)
日志中的报红
![你好，很高兴收到你的回复，按照你说的我重新进行了clone，但是依旧与之前一样无法运行，
![J}4}0YI)MLN40F}I7F1PC$H](https://github.com/wangchenyan/ponymusic/assets/132640475/91da70cb-f2ad-4b4b-b8d7-d46b044c006e)
代码中的libs似乎有问题，
![K%(B@_(O}$_PL {BWHVO JT](https://github.com/wangchenyan/ponymusic/assets/132640475/c3bd1ca4-9f27-4e58-ba51-91a989e7f769)
我不知道该如何处理，AS提示我将gradle插件版本从7.4.2更新到8.3.2，
![image](https://github.com/wangchenyan/ponymusic/assets/132640475/9347b59d-554f-4422-9941-4c9da60e6679)
我之前尝试过，可以解决libs的爆红，但是这又会产生新的问题，由于版本更新后8.0以上的gradle插件会弃用auto-register的相关模块，这导致了项目无法运行成功，所以我不知道该如何在不更新gradle插件的前提下解决libs报错问题，另外不知道为什么这个jar包下会有这么多的报错
![S@LVJJSZIKAUKH09J0VG`P](https://github.com/wangchenyan/ponymusic/assets/132640475/4be7bee9-ad31-4c27-98d8-8f37127b7dfc)
![%H4YSD2888 EA$%PWBY7{7Y](https://github.com/wangchenyan/ponymusic/assets/132640475/7107fa26-501d-4fa2-a906-7c3878e5ab38)
sync过后AS给的警告也和版本有关
![image](https://github.com/wangchenyan/ponymusic/assets/132640475/fa32f3c5-dbe7-4358-b27b-b4b920e56678)
![image](https://github.com/wangchenyan/ponymusic/assets/132640475/31e20a96-5de2-417e-9632-1376f65f8dcc)
日志中的报红
![你好，很高兴收到你的回复，按照你说的我重新进行了clone，但是依旧与之前一样无法运行，
![J}4}0YI)MLN40F}I7F1PC$H](https://github.com/wangchenyan/ponymusic/assets/132640475/91da70cb-f2ad-4b4b-b8d7-d46b044c006e)
代码中的libs似乎有问题，
![K%(B@_(O}$_PL {BWHVO JT](https://github.com/wangchenyan/ponymusic/assets/132640475/c3bd1ca4-9f27-4e58-ba51-91a989e7f769)
我不知道该如何处理，AS提示我将gradle插件版本从7.4.2更新到8.3.2，
![image](https://github.com/wangchenyan/ponymusic/assets/132640475/9347b59d-554f-4422-9941-4c9da60e6679)
我之前尝试过，可以解决libs的爆红，但是这又会产生新的问题，由于版本更新后8.0以上的gradle插件会弃用auto-register的相关模块，这导致了项目无法运行成功，所以我不知道该如何在不更新gradle插件的前提下解决libs报错问题，另外不知道为什么这个jar包下会有这么多的报错
![S@LVJJSZIKAUKH09J0VG`P](https://github.com/wangchenyan/ponymusic/assets/132640475/4be7bee9-ad31-4c27-98d8-8f37127b7dfc)
![%H4YSD2888 EA$%PWBY7{7Y](https://github.com/wangchenyan/ponymusic/assets/132640475/7107fa26-501d-4fa2-a906-7c3878e5ab38)
sync过后AS给的警告也和版本有关
![image](https://github.com/wangchenyan/ponymusic/assets/132640475/fa32f3c5-dbe7-4358-b27b-b4b920e56678)
![image](https://github.com/wangchenyan/ponymusic/assets/132640475/31e20a96-5de2-417e-9632-1376f65f8dcc)
日志中的报红
P(C)4IX}R1}{ $RW2TW)U](https://github.com/wangchenyan/ponymusic/assets/132640475/41f7e870-475c-420e-bc00-3636523f74a3)
我的AS版本
![image](https://github.com/wangchenyan/ponymusic/assets/132640475/879adf2e-8e70-4759-848d-01bf3bef5d9b)

**Comment by ljf1989** [comment]
> 求能正常运行该项目的gradle和gradle插件以及JDK的版本

替换distributionUrl
https://www.cnblogs.com/fanqisoft/p/17529061.html
File-->project structure -->sdk location-->gradle-setting--gradle-gdk 改为17

**Comment by wangchenyan** [comment]
@YanZeno 用楼上的方法试试能解决吗

**Comment by YanZeno** [comment]
谢谢大家的回复，不知道为什么又运行出来了。虽然libs下还是有红色波浪，也有关于auto-register相关模块的警告以及不断的gradle更新提示，但是只要不更新到8.0以上就可以运行了。不过可惜那个网易云音乐API被封了。今天端午节，祝大家端午安康哈哈

**Comment by wangchenyan** [comment]
@YanZeno 你好，最新代码已经去除auto-register依赖，并且已经升级到AGP8.4，可以更新代码试试，libs也不会飘红了

**Comment by wangchenyan** [comment]
@YanZeno 关于API被封的问题，可以在github搜索一下，有一个备份项目可以继续使用
