### ISSUE TITLE
通知可以支持自定义的按钮吗，例如增加一个可以切换播放模式的按钮

### ISSUE THREAD

**Issue by aikorola** [ChanWong21/PonyMusic#89]

**Comment by wangchenyan** [comment]
自定义通知栏可以添加按钮，系统通知栏貌似不行，你可以在自定义通知中增加一个，可以参考：https://github.com/wangchenyan/ponymusic/blob/57c8d9f/app/src/main/java/me/wcy/music/service/PlayService.kt#L221

**Comment by aikorola** [comment]
这个的效果没有系统通知栏的好，已经找到方式啦
https://github.com/z-huang/InnerTune/blob/dev/app/src/main/java/com/zionhuang/music/playback/MusicService.kt
