### ISSUE TITLE
播放在线音乐然后返回主界面，想进入播放界面会crash

### ISSUE THREAD

**Issue by sosodespicable** [ChanWong21/PonyMusic#9]

**Comment by sosodespicable** [comment]
随便播放一个在线音乐，之后退回主界面，点击下面的播放控件想进入播放界面，会crash，NullPointException，之后重启程序也会crash

**Comment by wangchenyan** [comment]
@sosodespicable 你好，请你pull最新的代码然后再试一下，如果已经是最新代码，可否麻烦贴一下crash日志？

**Comment by wangchenyan** [comment]
你好，这个问题已经修复了，麻烦pull最新代码。
